### ISSUE TITLE
请教大佬 5.15内核有遇过没法启动 Adbyby Plus+

### ISSUE THREAD

**Issue by mitsukileung** [lovehackintosh/lede#13]
AX3600和AX6都一样结果，但在 5.10 内核 可以启动

**Comment by misaka36** [comment]
adbyby不支持arm64 v8架构，ssrplus内置更好的去广告插件
<img width="515" alt="截屏2022-11-29 15 19 54" src="https://user-images.githubusercontent.com/92633080/204464752-74807b52-16e3-4797-adee-215f66c0b851.png">
